
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: josdk-crd-validating-cluster-role
  namespace: test
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
    verbs:
      - '*'
---
apiVersion: v1
data:
  KFREEZER_S3_URL: http://snapshot-repository
  KFREEZER_S3_BUCKET: kfreezer
  KFREEZER_S3_ACCESSKEY: minio_access_key
  KFREEZER_S3_SECRETKEY: minio_secret_key
kind: ConfigMap
metadata:
  name: kfreezer-cm
