apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-job-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
#  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: test
spec:
  template:
    spec:
      volumes:
        - name: image
          persistentVolumeClaim:
            claimName: test-job-pvc
      containers:
        - name: counting
          image: core.harbor.10.131.36.2.nip.io/oaas/counting
          volumeMounts:
            - mountPath: /snapshot-images
              name: image
          args:
            - 'fastfreeze run --image-url file:/snapshot-images/test-job -- python -u ./main.py'
          securityContext:
            capabilities:
              add:
#                - CAP_SYS_PTRACE
                - ALL
#            privileged: true
#            allowPrivilegeEscalation: true
      restartPolicy: Never

#  backoffLimit: 4

# kubectl exec -n test test-job--1-9jsvd -- fastfreeze checkpoint --leave-running
