apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: counting
          image: core.harbor.10.131.36.2.nip.io/migration/memhog-fastfreeze
          env:
            - name: SHOULD_CONTINUE
              value: 'true'
            - name: MEMORY_LIMIT
              value: '1024'
            - name: MEMORY_INCREMENT
              value: '128'
          securityContext:
            capabilities:
              add:
                - ALL
      restartPolicy: Never

